# Generated by Django 3.1.4 on 2021-06-07 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0038_auto_20210429_0920'),
    ]

    operations = [
        migrations.AddField(
            model_name='hub_test',
            name='courseid21_no1_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hub_test',
            name='courseid21_no2_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hub_test',
            name='courseid21_no3_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hub_test',
            name='courseid21_no4_score',
            field=models.IntegerField(default=0),
        ),
    ]
