# Generated by Django 3.1.4 on 2021-06-07 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0039_auto_20210607_1540'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hub_test',
            name='courseid21_no1_score',
        ),
        migrations.RemoveField(
            model_name='hub_test',
            name='courseid21_no2_score',
        ),
        migrations.RemoveField(
            model_name='hub_test',
            name='courseid21_no3_score',
        ),
        migrations.RemoveField(
            model_name='hub_test',
            name='courseid21_no4_score',
        ),
        migrations.AddField(
            model_name='evaluate_t',
            name='courseid21_no1_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='evaluate_t',
            name='courseid21_no2_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='evaluate_t',
            name='courseid21_no3_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='evaluate_t',
            name='courseid21_no4_score',
            field=models.IntegerField(default=0),
        ),
    ]
