# Generated by Django 3.0.7 on 2021-06-08 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0040_auto_20210607_1547'),
    ]

    operations = [
        migrations.CreateModel(
            name='virtual_class',
            fields=[
                ('PK_id', models.AutoField(primary_key=True, serialize=False)),
                ('Activity_name', models.CharField(max_length=250, null=True)),
                ('Activity_generation', models.IntegerField(default=1)),
                ('Date_zoom', models.DateField()),
                ('Time_zoom', models.TimeField()),
                ('lecturer_name', models.CharField(max_length=500, null=True)),
                ('Num_people', models.IntegerField(default=0)),
                ('Status', models.BooleanField(default=True)),
            ],
        ),
    ]
