# Generated by Django 3.0.7 on 2021-06-08 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0041_virtual_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtual_class',
            name='Endtime_zoom',
            field=models.TimeField(default='00:00'),
        ),
    ]
