# Generated by Django 3.1.4 on 2021-06-10 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0042_virtual_class_endtime_zoom'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff_score',
            name='Check_policy',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='staff_score',
            name='Status',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
