# Generated by Django 3.1.4 on 2021-06-14 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0044_staff_short_part_dept'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='Short_Part_Dept',
            field=models.CharField(default='สายงาน', max_length=10, null=True),
        ),
    ]
