# Generated by Django 3.1.4 on 2021-06-14 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0046_auto_20210614_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='StaffPosition',
            field=models.CharField(default='ตำแหน่ง', max_length=20, null=True),
        ),
    ]
