# Generated by Django 3.0.7 on 2021-06-23 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0048_auto_20210623_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='End_date',
            field=models.DateField(default='2021-11-30'),
        ),
        migrations.AddField(
            model_name='course',
            name='Start_date',
            field=models.DateField(default='2021-06-01'),
        ),
        migrations.AddField(
            model_name='course',
            name='Total_people',
            field=models.IntegerField(default=838),
        ),
    ]
