# Generated by Django 3.0.7 on 2021-06-24 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0049_auto_20210623_1544'),
    ]

    operations = [
        migrations.CreateModel(
            name='county',
            fields=[
                ('PK_ID', models.AutoField(primary_key=True, serialize=False)),
                ('county_name', models.CharField(max_length=10, null=True)),
                ('max_number', models.IntegerField(default=0, null=True)),
                ('current_number', models.IntegerField(default=0, null=True)),
                ('percent_number', models.FloatField(blank=True, default=0.0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dept',
            fields=[
                ('PK_ID', models.AutoField(primary_key=True, serialize=False)),
                ('listname', models.CharField(max_length=10, null=True)),
                ('max_number', models.IntegerField(default=0, null=True)),
                ('current_number', models.IntegerField(default=0, null=True)),
                ('percent_number', models.FloatField(blank=True, default=0.0, null=True)),
            ],
        ),
    ]
