from django.db import models

class Course(models.Model):
    CourseName = models.CharField(max_length=100)
    CourseBy = models.CharField(max_length=50)
    Couse_Sub_Total = models.IntegerField(null=True, default=0)
    Date_Created = models.DateTimeField(auto_now_add=True, null=True)
    CourseStatus = models.CharField(null=True,max_length=3,default='OFF')

class Sub_Course(models.Model):
    Title = models.CharField(max_length=100)
    ConstructorName = models.CharField(max_length=100, null=True)
    ConstructorPosition = models.CharField(max_length=100, null=True)
    Tel = models.CharField(max_length=7,null=True,default='0000')
    email = models.EmailField(null=True, default='uuu@pea.co.th')
    Document = models.URLField(max_length=300, null=True)
    URLGdrive = models.URLField(max_length=300, null=True)
    TotalTime =models.IntegerField(null=True, default=0)
    Date_Created = models.DateField(auto_now_add=True, null=True)
    Link_Course = models.ForeignKey(Course,related_name='Sub_Courses',on_delete = models.CASCADE,null= True)

class Course_Pretest(models.Model):
    TestTitle = models.CharField(max_length=300)
    Test1 = models.CharField(max_length=200, null=True)
    Test2 = models.CharField(max_length=200, null=True)
    Test3 = models.CharField(max_length=200, null=True)
    Test4 = models.CharField(max_length=200, null=True)
    Test_Course = models.ForeignKey(Course,related_name='Courses',on_delete = models.CASCADE,null= True)

class Check(models.Model):
    StaffID = models.CharField(max_length=10, unique=True, primary_key=True)
    Error_Detail = models.CharField(max_length=200, null=True)
    Date_check = models.DateTimeField(auto_now_add=True, null=True)

class Staff(models.Model):
    StaffID = models.CharField(max_length=10, unique=True, primary_key=True)
    StaffName = models.CharField(max_length=150)
    StaffPosition = models.CharField(max_length=10,null=True)
    StaffLevelcode = models.CharField(max_length=5,null=True)
    StaffDepshort = models.CharField(max_length=200)
    DeptCode = models.CharField(max_length=50)
    Organization = models.CharField(max_length=100)
    Date_Start = models.DateTimeField(auto_now_add=False, null=True)
    Status = models.CharField(max_length=12, default='on Process', null=True)

class Staff_Score(models.Model):
    Pre_Created1 = models.DateTimeField(auto_now_add=False, null= True)
    Pre_Score1 = models.IntegerField(null=True, default=0)
    Post_Created1 = models.DateTimeField(auto_now_add=False, null= True)
    Post_Score1 = models.IntegerField(null=True, default=0)
    Pre_Created2 = models.DateTimeField(auto_now_add=False, null= True)
    Pre_Score2 = models.IntegerField(null=True, default=0)
    Post_Created2 = models.DateTimeField(auto_now_add=False, null= True)
    Post_Score2 = models.IntegerField(null=True, default=0)
    Pre_Created3 = models.DateTimeField(auto_now_add=False, null= True)
    Pre_Score3 = models.IntegerField(null=True, default=0)
    Post_Created3 = models.DateTimeField(auto_now_add=False, null= True)
    Post_Score3 = models.IntegerField(null=True, default=0)
    Pre_Created4 = models.DateTimeField(auto_now_add=False, null= True)
    Pre_Score4 = models.IntegerField(null=True, default=0)
    Post_Created4 = models.DateTimeField(auto_now_add=False, null= True)
    Post_Score4 = models.IntegerField(null=True, default=0)
    Pre_Created5 = models.DateTimeField(auto_now_add=False, null= True)
    Pre_Score5 = models.IntegerField(null=True, default=0)
    Post_Created5 = models.DateTimeField(auto_now_add=False, null= True)
    Post_Score5 = models.IntegerField(null=True, default=0)
    Pre_Created6 = models.DateTimeField(auto_now_add=False, null= True)
    Pre_Score6 = models.IntegerField(null=True, default=0)
    Post_Created6 = models.DateTimeField(auto_now_add=False, null= True)
    Post_Score6 = models.IntegerField(null=True, default=0)
    Pre_Created7 = models.DateTimeField(auto_now_add=False, null= True)
    Pre_Score7 = models.IntegerField(null=True, default=0)
    Post_Created7 = models.DateTimeField(auto_now_add=False, null= True)
    Post_Score7 = models.IntegerField(null=True, default=0)
    Pre_Created8 = models.DateTimeField(auto_now_add=False, null= True)
    Pre_Score8 = models.IntegerField(null=True, default=0)
    Post_Created8 = models.DateTimeField(auto_now_add=False, null= True)
    Post_Score8 = models.IntegerField(null=True, default=0)
    Pre_Created9 = models.DateTimeField(auto_now_add=False, null= True)
    Pre_Score9 = models.IntegerField(null=True, default=0)
    Post_Created9 = models.DateTimeField(auto_now_add=False, null= True)
    Post_Score9 = models.IntegerField(null=True, default=0)
    Pre_Created10 = models.DateTimeField(auto_now_add=False, null= True)
    Pre_Score10 = models.IntegerField(null=True, default=0)
    Post_Created10 = models.DateTimeField(auto_now_add=False, null= True)
    Post_Score10 = models.IntegerField(null=True, default=0)
    Staff = models.ForeignKey(Staff, related_name= 'Staff_score', on_delete= models.CASCADE,null= True)

class Staff_Vdolog(models.Model):
    Date_Created = models.DateTimeField(auto_now_add=False, null= True)
    Status = models.CharField(max_length=12, default='on Process', null=True)
    Link_SubCourse = models.ForeignKey(Sub_Course, related_name='SubCourse_Vdo', on_delete=models.CASCADE,null= True)
    Link_course = models.ForeignKey(Course, related_name='Course_Vdo', on_delete=models.CASCADE,null= True)
    Staff = models.ForeignKey(Staff, related_name= 'Staff_Vdo', on_delete= models.CASCADE,null= True)


